/*
  OUR LONDON SPOTS
  cat: "food" = red pin (restaurants, cafés, bars, pubs)
       "do"   = blue pin (museums, cinema, lectures, streets to wander)
       "shop" = black pin (bookshops, antiques, vintage, markets)
       "home" = green house pin (our hotel)
  photo: our own pictures live in the photos/ folder (e.g. "photos/kismet.jpg"); the others are free Wikimedia photos with a credit
  link:  optional, e.g. the Instagram reel or the website
*/
const SPOTS = [
  /* ---------- OUR HOTEL ---------- */
  {name:"Zedwell Greenwich", cat:"home", kind:"Our hotel", area:"Greenwich / Deptford Bridge",
   lat:51.48092, lng:-0.01946, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Deptford_Bridge_DLR_station_2023-04-26.jpg/960px-Deptford_Bridge_DLR_station_2023-04-26.jpg", credit:{"by": "Darianthomson", "license": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:Deptford_Bridge_DLR_station_2023-04-26.jpg"}, photoNote:"Deptford Bridge DLR, the station next to the hotel", link:"",
   note:"Cavatina Point, 7 Harmony Place, SE8 3FB. Nearest stops: Deptford Bridge (DLR) and Greenwich (DLR + trains to London Bridge)."},

  /* ---------- MUSEUMS & CULTURE (blue) ---------- */
  {name:"Tate Britain", cat:"do", kind:"Museum · exhibition", area:"Millbank / Pimlico",
   lat:51.49106, lng:-0.12779, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Tate_Britain_2020.jpg/960px-Tate_Britain_2020.jpg", credit:{"by": "Julian Herzog", "license": "CC BY 4.0", "url": "https://commons.wikimedia.org/wiki/File:Tate_Britain_2020.jpg"}, link:"",
   note:"For 'The 90s: Art and Fashion', on from 8 October 2026 to 14 February 2027 (ticketed). The main collection is free."},
  {name:"Design Museum", cat:"do", kind:"Museum", area:"Kensington High Street",
   lat:51.49990, lng:-0.20024, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Design_Museum,_Kensington,_London,_March_2017_(04).JPG/960px-Design_Museum,_Kensington,_London,_March_2017_(04).JPG", credit:{"by": "Ardfern", "license": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:Design_Museum,_Kensington,_London,_March_2017_(04).JPG"}, link:"",
   note:"Design, architecture and fashion. The permanent collection on the top floor is free; special exhibitions are ticketed."},
  {name:"V&A East Storehouse", cat:"do", kind:"Museum", area:"Queen Elizabeth Olympic Park, Stratford",
   lat:51.54642, lng:-0.02120, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/V%26A_East_Storehouse_interior_2025-08-17_(2).jpg/960px-V%26A_East_Storehouse_interior_2025-08-17_(2).jpg", credit:{"by": "The wub", "license": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:V%26A_East_Storehouse_interior_2025-08-17_(2).jpg"}, link:"",
   note:"A walk-through storehouse with a LOT of objects from the V&A collection. Free."},
  {name:"British Museum", cat:"do", kind:"Museum", area:"Bloomsbury",
   lat:51.51941, lng:-0.12696, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/British_Museum_(20497855643).jpg/960px-British_Museum_(20497855643).jpg", credit:{"by": "Elliott Brown", "license": "CC BY-SA 2.0", "url": "https://commons.wikimedia.org/wiki/File:British_Museum_(20497855643).jpg"}, link:"",
   note:"Free entry, but book a time slot online in advance."},
  {name:"Prince Charles Cinema", cat:"do", kind:"Cinema", area:"Leicester Square",
   lat:51.51145, lng:-0.13020, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Prince_Charles_Cinema,_Leicester_Square,_WC2_(2355497573).jpg/960px-Prince_Charles_Cinema,_Leicester_Square,_WC2_(2355497573).jpg", credit:{"by": "Ewan Munro", "license": "CC BY-SA 2.0", "url": "https://commons.wikimedia.org/wiki/File:Prince_Charles_Cinema,_Leicester_Square,_WC2_(2355497573).jpg"}, link:"",
   note:"Retro films, classics, cult movies and marathons. Cheap tickets."},
  {name:"Gresham College", cat:"do", kind:"Public lectures", area:"Holborn",
   lat:51.51754, lng:-0.10988, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Barnard's_Inn_Hall_(Gresham_College).jpg/960px-Barnard's_Inn_Hall_(Gresham_College).jpg", credit:{"by": "Jamesfranklingresham", "license": "CC BY-SA 3.0", "url": "https://commons.wikimedia.org/wiki/File:Barnard's_Inn_Hall_(Gresham_College).jpg"}, photoNote:"Barnard's Inn Hall, where many lectures take place", link:"",
   note:"Free public lectures, many held in the historic Barnard's Inn Hall. Check the lecture calendar for dates."},

  {name:"Courtauld Gallery", cat:"do", kind:"Museum", area:"Somerset House, Strand",
   lat:51.51159, lng:-0.11756, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Courtauld_Gallery,_Staircase.jpg/960px-Courtauld_Gallery,_Staircase.jpg", credit:{"by": "Mike Peel", "license": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:Courtauld_Gallery,_Staircase.jpg"}, link:"",
   note:"Small gallery with famous Impressionists: Manet, Monet, Van Gogh, Cézanne. Ticketed (about £14); book ahead."},

  /* ---------- STREETS TO WANDER (blue) ---------- */
  {name:"Notting Hill", cat:"do", kind:"Street to wander", area:"Notting Hill",
   lat:51.51330, lng:-0.20330, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Colourful_houses_in_Lancaster_Road,_Notting_Hill_2020-07-05.jpg/960px-Colourful_houses_in_Lancaster_Road,_Notting_Hill_2020-07-05.jpg", credit:{"by": "Bex Walton", "license": "CC BY 2.0", "url": "https://commons.wikimedia.org/wiki/File:Colourful_houses_in_Lancaster_Road,_Notting_Hill_2020-07-05.jpg"}, link:"",
   note:"Pastel houses and pretty side streets around Portobello Road."},
  {name:"Hampstead", cat:"do", kind:"Street to wander", area:"Hampstead",
   lat:51.55600, lng:-0.17800, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Flask_Walk,_Hampstead_2023-05-20.jpg/960px-Flask_Walk,_Hampstead_2023-05-20.jpg", credit:{"by": "David", "license": "CC BY 2.0", "url": "https://commons.wikimedia.org/wiki/File:Flask_Walk,_Hampstead_2023-05-20.jpg"}, photoNote:"Flask Walk", link:"",
   note:"Very nice streets with an autumn feel. Combine with the Holly Bush pub."},
  {name:"Redchurch Street", cat:"do", kind:"Street to wander", area:"Shoreditch",
   lat:51.52446, lng:-0.07457, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Redchurch_Street,_Shoreditch_-_geograph.org.uk_-_4341049.jpg/960px-Redchurch_Street,_Shoreditch_-_geograph.org.uk_-_4341049.jpg", credit:{"by": "Chris Whippet", "license": "CC BY-SA 2.0", "url": "https://commons.wikimedia.org/wiki/File:Redchurch_Street,_Shoreditch_-_geograph.org.uk_-_4341049.jpg"}, link:"",
   note:"Nice street in general: independent shops, street art, cafés."},
  {name:"Chiltern Street", cat:"do", kind:"Street to wander", area:"Marylebone",
   lat:51.52031, lng:-0.15557, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Chiltern_Street,_Marylebone_(2)_-_geograph.org.uk_-_5561976.jpg/960px-Chiltern_Street,_Marylebone_(2)_-_geograph.org.uk_-_5561976.jpg", credit:{"by": "Richard Vince", "license": "CC BY-SA 2.0", "url": "https://commons.wikimedia.org/wiki/File:Chiltern_Street,_Marylebone_(2)_-_geograph.org.uk_-_5561976.jpg"}, link:"",
   note:"Elegant little Marylebone street with boutiques."},
  {name:"Cecil Court (street with books)", cat:"do", kind:"Street with books", area:"Covent Garden",
   lat:51.51072, lng:-0.12784, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Cecil_Court_in_London_with_bookshops.jpg/960px-Cecil_Court_in_London_with_bookshops.jpg", credit:{"by": "VirtuallyLondonBecky", "license": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:Cecil_Court_in_London_with_bookshops.jpg"}, link:"",
   note:"The book street. The original 'Booksellers' Row' was demolished around 1900; Cecil Court is today's version, lined with antiquarian bookshops."},

  /* ---------- SHOPS (black) ---------- */
  {name:"Brick Lane Bookshop", cat:"shop", kind:"Bookshop", area:"Brick Lane",
   lat:51.52234, lng:-0.07151, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Brick_Lane_Bookshop.jpg/960px-Brick_Lane_Bookshop.jpg", credit:{"by": "Martin Hearn", "license": "CC BY 2.0", "url": "https://commons.wikimedia.org/wiki/File:Brick_Lane_Bookshop.jpg"}, link:"",
   note:"Independent bookshop, nice postcards."},
  {name:"Libreria", cat:"shop", kind:"Bookshop", area:"Spitalfields",
   lat:51.52038, lng:-0.07064, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Libreria_Bookshop.jpg/960px-Libreria_Bookshop.jpg", credit:{"by": "Bea Phi", "license": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:Libreria_Bookshop.jpg"}, link:"",
   note:"Very pretty bookshop with mirrored shelves. Phone-free inside."},
  {name:"Alfies Antique Market", cat:"shop", kind:"Antiques & jewellery", area:"Marylebone",
   lat:51.52413, lng:-0.16883, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Alfies_Antiques_Market_(15558859763).jpg/960px-Alfies_Antiques_Market_(15558859763).jpg", credit:{"by": "eilidh_wag", "license": "CC BY 2.0", "url": "https://commons.wikimedia.org/wiki/File:Alfies_Antiques_Market_(15558859763).jpg"}, link:"",
   note:"Antiques market in an old department store, several floors plus a café upstairs. Closed Sun & Mon."},
  {name:"Old Spitalfields Market", cat:"shop", kind:"Market · antiques & vintage", area:"Spitalfields",
   lat:51.51966, lng:-0.07555, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Old_Spitalfields_Market_(3)_2024-12-21.jpg/960px-Old_Spitalfields_Market_(3)_2024-12-21.jpg", credit:{"by": "Andy Li", "license": "CC0", "url": "https://commons.wikimedia.org/wiki/File:Old_Spitalfields_Market_(3)_2024-12-21.jpg"}, link:"",
   note:"More spacious, open every day. Antiques on Thursdays. Spitalfields itself is a must!!"},
  {name:"Grays Antiques", cat:"shop", kind:"Antiques & jewellery", area:"Mayfair",
   lat:51.51370, lng:-0.14865, photo:"https://upload.wikimedia.org/wikipedia/commons/e/e2/Grays_Exterior.jpg", credit:{"by": "Aliadams23", "license": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:Grays_Exterior.jpg"}, link:"",
   note:"Antique jewellery dealers under one roof. Closed weekends."},
  {name:"Portobello Road Market", cat:"shop", kind:"Market · antiques & street food", area:"Notting Hill",
   lat:51.51700, lng:-0.20585, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Portobello_Road_Market_-_geograph.org.uk_-_4264976.jpg/960px-Portobello_Road_Market_-_geograph.org.uk_-_4264976.jpg", credit:{"by": "Roger Cornfoot", "license": "CC BY-SA 2.0", "url": "https://commons.wikimedia.org/wiki/File:Portobello_Road_Market_-_geograph.org.uk_-_4264976.jpg"}, link:"",
   note:"Cool street markets. Saturday is the big antiques day."},
  {name:"The Old Cinema", cat:"shop", kind:"Antiques & vintage", area:"Chiswick",
   lat:51.49288, lng:-0.25450, photo:"https://upload.wikimedia.org/wikipedia/commons/9/94/Chiswick_High_Road,_Chiswick_-_geograph.org.uk_-_2767206.jpg", credit:{"by": "Alex McGregor", "license": "CC BY-SA 2.0", "url": "https://commons.wikimedia.org/wiki/File:Chiswick_High_Road,_Chiswick_-_geograph.org.uk_-_2767206.jpg"}, photoNote:"Chiswick High Road, the street it's on", link:"",
   note:"Vintage furniture and curiosities in a former cinema, three floors."},
  {name:"Leadenhall Market", cat:"shop", kind:"Market", area:"City of London",
   lat:51.51277, lng:-0.08353, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Leadenhall_Market,_City_of_London_(Interior_-_01).jpg/960px-Leadenhall_Market,_City_of_London_(Interior_-_01).jpg", credit:{"by": "Doyle of London", "license": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:Leadenhall_Market,_City_of_London_(Interior_-_01).jpg"}, link:"",
   note:"For vintage lovers. Beautiful Victorian covered market."},
  {name:"Brick Lane vintage", cat:"shop", kind:"Vintage shopping", area:"Brick Lane",
   lat:51.52170, lng:-0.07170, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Hunky_Dory_Vintage_226_Brick_Lane_2022-03-06.jpg/960px-Hunky_Dory_Vintage_226_Brick_Lane_2022-03-06.jpg", credit:{"by": "Garry Knight", "license": "CC BY 2.0", "url": "https://commons.wikimedia.org/wiki/File:Hunky_Dory_Vintage_226_Brick_Lane_2022-03-06.jpg"}, link:"",
   note:"Vintage shops and markets along Brick Lane, around the Old Truman Brewery."},
  {name:"Kilburn High Road charity shops", cat:"shop", kind:"Vintage shopping", area:"Kilburn",
   lat:51.54135, lng:-0.19750, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Shops_on_Kilburn_High_Road_-_geograph.org.uk_-_7505618.jpg/960px-Shops_on_Kilburn_High_Road_-_geograph.org.uk_-_7505618.jpg", credit:{"by": "David Howard", "license": "CC BY-SA 2.0", "url": "https://commons.wikimedia.org/wiki/File:Shops_on_Kilburn_High_Road_-_geograph.org.uk_-_7505618.jpg"}, photoNote:"Kilburn High Road", link:"",
   note:"Oxfam (no. 181) and the £5 Cancer Research shop (no. 187) next to each other."},
  {name:"Uniqlo", cat:"shop", kind:"Clothes", area:"Oxford Street (Tottenham Court Rd)",
   lat:51.51625, lng:-0.13065, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Uniqlo_Regent_Street,_London.jpg/960px-Uniqlo_Regent_Street,_London.jpg", credit:{"by": "Mark from Woking", "license": "CC BY 2.0", "url": "https://commons.wikimedia.org/wiki/File:Uniqlo_Regent_Street,_London.jpg"}, photoNote:"The Regent Street branch", link:"",
   note:"One Oxford Street branch."},

  {name:"Keith Fawkes", cat:"shop", kind:"Secondhand books & antiques", area:"Hampstead",
   lat:51.55651, lng:-0.17771, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Keith_Fawkes.jpg/960px-Keith_Fawkes.jpg", credit:{"by": "It's No Game", "license": "CC BY 2.0", "url": "https://commons.wikimedia.org/wiki/File:Keith_Fawkes.jpg"}, link:"",
   note:"Secondhand bookshop and antiques, books stacked floor to ceiling. 1–3 Flask Walk. Closed Mondays."},

  {name:"Choosing Keeping", cat:"shop", kind:"Stationery", area:"Seven Dials / Covent Garden",
   lat:51.51315, lng:-0.12751, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Guild_House,_18_Tower_Street,_Seven_Dials,_Covent_Garden,_December_2022.jpg/960px-Guild_House,_18_Tower_Street,_Seven_Dials,_Covent_Garden,_December_2022.jpg", credit:{"by": "No Swan So Fine", "license": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:Guild_House,_18_Tower_Street,_Seven_Dials,_Covent_Garden,_December_2022.jpg"}, photoNote:"Tower Street, the street it's on", link:"",
   note:"Very nice stationery shop with an old London feeling: fountain pens, notebooks, beautiful papers."},

  /* ---------- FOOD: CHINATOWN (red) ---------- */
  {name:"Joy Bao", cat:"food", kind:"Bao (takeaway)", area:"Chinatown",
   lat:51.51193, lng:-0.12930, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/21-24_Newport_Court,_Chinatown,_March_2022.jpg/960px-21-24_Newport_Court,_Chinatown,_March_2022.jpg", credit:{"by": "No Swan So Fine", "license": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:21-24_Newport_Court,_Chinatown,_March_2022.jpg"}, photoNote:"Newport Court, where the kiosk is", link:"",
   note:"Super nice bao for only £3.50!! Takeaway only."},
  {name:"Four Seasons", cat:"food", kind:"Chinese restaurant", area:"Chinatown",
   lat:51.51194, lng:-0.13096, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Four_Seasons,_Chinatown,_W1_(7293681834).jpg/960px-Four_Seasons,_Chinatown,_W1_(7293681834).jpg", credit:{"by": "Ewan Munro", "license": "CC BY-SA 2.0", "url": "https://commons.wikimedia.org/wiki/File:Four_Seasons,_Chinatown,_W1_(7293681834).jpg"}, link:"",
   note:"Classic Chinese restaurant, known for its roast duck."},
  {name:"Q Beef Noodles", cat:"food", kind:"Noodles", area:"Chinatown / Soho",
   lat:51.51290, lng:-0.13115, photo:"https://upload.wikimedia.org/wikipedia/commons/b/ba/22-24_Romilly_Street_(geograph_5703493).jpg", credit:{"by": "Stephen Richards", "license": "CC BY-SA 2.0", "url": "https://commons.wikimedia.org/wiki/File:22-24_Romilly_Street_(geograph_5703493).jpg"}, photoNote:"The building on Romilly Street (older photo)", link:"",
   note:"Hand-pulled noodles with beef. Can get busy."},
  {name:"Borough Market", cat:"food", kind:"Food market", area:"London Bridge",
   lat:51.50558, lng:-0.09048, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Borough_Market_(4701274756).jpg/960px-Borough_Market_(4701274756).jpg", credit:{"by": "Jeremy Keith", "license": "CC BY 2.0", "url": "https://commons.wikimedia.org/wiki/File:Borough_Market_(4701274756).jpg"}, link:"",
   note:"Street food heaven. Closed Mondays; go early on weekends."},

  /* ---------- FOOD: CAFÉ & RESTAURANTS (red) ---------- */
  {name:"Townhouse", cat:"food", kind:"Café", area:"Spitalfields",
   lat:51.51932, lng:-0.07394, photo:"photos/townhouse.jpg", link:"",
   note:"Very antique and comfy, with a café downstairs in a very old kitchen. Closed Mondays."},
  {name:"Vesper", cat:"food", kind:"Restaurant", area:"Exmouth Market",
   lat:51.52519, lng:-0.11009, photo:"photos/vesper.jpg", link:"",
   note:"Very clean and with candlelight."},
  {name:"Kismet", cat:"food", kind:"Restaurant (Turkish)", area:"Borough",
   lat:51.50548, lng:-0.08989, photo:"photos/kismet.jpg", link:"",
   note:"Brick walls, warm lighting, photos on the wall. Above the Globe Tavern at Borough Market."},
  {name:"Auguste", cat:"food", kind:"Restaurant (Italian)", area:"London Fields / Hackney",
   lat:51.53952, lng:-0.05782, photo:"photos/auguste.jpg", link:"",
   note:"Art, wine bottles, Italian."},
  {name:"French Society", cat:"food", kind:"Restaurant (French)", area:"West Hampstead",
   lat:51.55214, lng:-0.19604, photo:"https://upload.wikimedia.org/wikipedia/commons/7/71/Mill_Lane,_West_Hampstead_-_geograph.org.uk_-_40290.jpg", credit:{"by": "David Hawgood", "license": "CC BY-SA 2.0", "url": "https://commons.wikimedia.org/wiki/File:Mill_Lane,_West_Hampstead_-_geograph.org.uk_-_40290.jpg"}, photoNote:"Mill Lane, the street it's on", link:"",
   note:"French bistro vibes."},
  {name:"Mountain", cat:"food", kind:"Restaurant", area:"Soho",
   lat:51.51202, lng:-0.13823, photo:"photos/mountain.jpg", link:"",
   note:"Warm lunch, super nice!!"},
  {name:"The Fat Badger", cat:"food", kind:"Restaurant", area:"Notting Hill",
   lat:51.52100, lng:-0.20933, photo:"photos/fat-badger.jpg", link:"",
   note:"Very warm and wood."},
  {name:"The Pelican", cat:"food", kind:"Pub & restaurant", area:"Notting Hill",
   lat:51.51879, lng:-0.20471, photo:"photos/pelican.jpg", link:"",
   note:"Pub-restaurant on All Saints Road."},
  {name:"The Walmer Castle", cat:"food", kind:"Pub & restaurant", area:"Notting Hill",
   lat:51.51518, lng:-0.19916, photo:"photos/walmer-castle.jpg", link:"",
   note:"Open fire."},
  {name:"The Parakeet", cat:"food", kind:"Pub & restaurant", area:"Kentish Town",
   lat:51.54978, lng:-0.14049, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Parakeet,_Kentish_Town,_NW5.jpg/960px-Parakeet,_Kentish_Town,_NW5.jpg", credit:{"by": "Ewan Munro", "license": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:Parakeet,_Kentish_Town,_NW5.jpg"}, link:"",
   note:"Pub-restaurant; book ahead."},

  /* ---------- FOOD: BARS (red) ---------- */
  {name:"Owl & Pussycat", cat:"food", kind:"Pub", area:"Shoreditch",
   lat:51.52430, lng:-0.07549, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Owl_and_Pussycat,_Shoreditch,_E2.jpg/960px-Owl_and_Pussycat,_Shoreditch,_E2.jpg", credit:{"by": "Ewan-M", "license": "CC BY-SA 2.0", "url": "https://commons.wikimedia.org/wiki/File:Owl_and_Pussycat,_Shoreditch,_E2.jpg"}, link:"",
   note:"Pub on Redchurch Street."},
  {name:"The Umbrella Workshop (Umbrella Project)", cat:"food", kind:"Cocktail bar", area:"Shoreditch",
   lat:51.52609, lng:-0.07715, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Cleeve_Workshops,_Rear_Of_Cleeve_House,_Boundary_Street_Estate.jpg/960px-Cleeve_Workshops,_Rear_Of_Cleeve_House,_Boundary_Street_Estate.jpg", credit:{"by": "Jwslubbock", "license": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:Cleeve_Workshops,_Rear_Of_Cleeve_House,_Boundary_Street_Estate.jpg"}, photoNote:"Cleeve Workshops, the courtyard where it's hidden", link:"",
   note:"Tiny hidden cocktail bar, menu changes weekly."},
  {name:"Seed Library", cat:"food", kind:"Cocktail bar", area:"Shoreditch",
   lat:51.52543, lng:-0.07729, photo:"photos/seed-library.jpg", link:"",
   note:"Cosy cocktail bar. Opens in the evening, closed Mon & Tue."},
  {name:"Ellie's", cat:"food", kind:"Bar", area:"Kingsland Road, Dalston",
   lat:51.54208, lng:-0.07585, photo:"photos/ellies.jpg", link:"",
   note:"Red lamps, super romantic, £8 martinis."},
  {name:"Mikkeller Bar", cat:"food", kind:"Beer bar", area:"Shoreditch",
   lat:51.52732, lng:-0.07694, photo:"photos/mikkeller.jpg", link:"",
   note:"Crisp pint and nice snacks."},

  /* ---------- FOOD: COZY PUBS (red) ---------- */
  {name:"The Holly Bush", cat:"food", kind:"Cozy pub", area:"Hampstead",
   lat:51.55786, lng:-0.17931, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/The_Holly_Bush_Pub,_Holly_Mount,_Hampstead,_London_2023-05-20.jpg/960px-The_Holly_Bush_Pub,_Holly_Mount,_Hampstead,_London_2023-05-20.jpg", credit:{"by": "David", "license": "CC BY 2.0", "url": "https://commons.wikimedia.org/wiki/File:The_Holly_Bush_Pub,_Holly_Mount,_Hampstead,_London_2023-05-20.jpg"}, link:"",
   note:"Cozy old pub tucked up a Hampstead lane."},
  {name:"The Trafalgar", cat:"food", kind:"Cozy pub", area:"Chelsea (King's Road)",
   lat:51.48786, lng:-0.16816, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Shops_on_King's_Road,_Chelsea_-_geograph.org.uk_-_5813102.jpg/960px-Shops_on_King's_Road,_Chelsea_-_geograph.org.uk_-_5813102.jpg", credit:{"by": "David Howard", "license": "CC BY-SA 2.0", "url": "https://commons.wikimedia.org/wiki/File:Shops_on_King's_Road,_Chelsea_-_geograph.org.uk_-_5813102.jpg"}, photoNote:"King's Road, the street it's on", link:"",
   note:"Cozy pub on King's Road."},
  {name:"The Audley Public House", cat:"food", kind:"Cozy pub", area:"Mayfair",
   lat:51.50972, lng:-0.15163, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Audley,_Mayfair,_W1.jpg/960px-Audley,_Mayfair,_W1.jpg", credit:{"by": "Ewan-M", "license": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:Audley,_Mayfair,_W1.jpg"}, link:"",
   note:"Painted ceiling, known for its Guinness."},
  {name:"Daly's", cat:"food", kind:"Cozy pub", area:"Strand / Temple (near Holborn)",
   lat:51.51308, lng:-0.11313, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Daly's_Wine_Bar_and_Beer_Hall,_Strand,_WC2_-_2025-10-07.jpg/960px-Daly's_Wine_Bar_and_Beer_Hall,_Strand,_WC2_-_2025-10-07.jpg", credit:{"by": "Ewan-M", "license": "CC BY-SA 4.0", "url": "https://commons.wikimedia.org/wiki/File:Daly's_Wine_Bar_and_Beer_Hall,_Strand,_WC2_-_2025-10-07.jpg"}, link:"",
   note:"Wine bar & beer hall."},
  {name:"The Old Queen's Head", cat:"food", kind:"Cozy pub", area:"Angel / Islington",
   lat:51.53721, lng:-0.10037, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/The_Old_Queens_Head_44_Essex_Road_-_2025-05-25.jpg/960px-The_Old_Queens_Head_44_Essex_Road_-_2025-05-25.jpg", credit:{"by": "Robert Scarth", "license": "CC BY-SA 2.0", "url": "https://commons.wikimedia.org/wiki/File:The_Old_Queens_Head_44_Essex_Road_-_2025-05-25.jpg"}, link:"",
   note:"Cozy pub on Essex Road."},
  {name:"Ye Olde Cheshire Cheese", cat:"food", kind:"Cozy pub", area:"Fleet Street",
   lat:51.51437, lng:-0.10717, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Ye_Olde_Cheshire_Cheese,_London_-_geograph.org.uk_-_4759346.jpg/960px-Ye_Olde_Cheshire_Cheese,_London_-_geograph.org.uk_-_4759346.jpg", credit:{"by": "Peter Trimming", "license": "CC BY-SA 2.0", "url": "https://commons.wikimedia.org/wiki/File:Ye_Olde_Cheshire_Cheese,_London_-_geograph.org.uk_-_4759346.jpg"}, link:"",
   note:"One of London's oldest pubs, rebuilt in 1667. Go down to the cellar rooms."},
  {name:"The Sherlock Holmes", cat:"food", kind:"Cozy pub", area:"Embankment",
   lat:51.50737, lng:-0.12518, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/The_Sherlock_Holmes_Public_House,_Northumberland_Street,_London_SW1_-_geograph.org.uk_-_4284618.jpg/960px-The_Sherlock_Holmes_Public_House,_Northumberland_Street,_London_SW1_-_geograph.org.uk_-_4284618.jpg", credit:{"by": "Christine Matthews", "license": "CC BY-SA 2.0", "url": "https://commons.wikimedia.org/wiki/File:The_Sherlock_Holmes_Public_House,_Northumberland_Street,_London_SW1_-_geograph.org.uk_-_4284618.jpg"}, link:"",
   note:"Victorian pub full of Sherlock memorabilia."},
  {name:"The Old Bank of England", cat:"food", kind:"Cozy pub", area:"Fleet Street",
   lat:51.51390, lng:-0.11148, photo:"https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/The_Old_Bank_of_England_Pub,_Fleet_Street,_London_-_Interior_2022-08-13.jpg/960px-The_Old_Bank_of_England_Pub,_Fleet_Street,_London_-_Interior_2022-08-13.jpg", credit:{"by": "David", "license": "CC BY 2.0", "url": "https://commons.wikimedia.org/wiki/File:The_Old_Bank_of_England_Pub,_Fleet_Street,_London_-_Interior_2022-08-13.jpg"}, link:"",
   note:"Pub in a grand former bank hall."}
];
